<?php

/**
 * @file
 * Contains tingkat.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tingkat_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tingkat module.
    case 'help.page.tingkat':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Tingkat perlomaab yang diikuti') . '</p>';
      return $output;

    default:
  }
}
