<?php

/**
 * @file
 * Contains penyelenggara.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function penyelenggara_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the penyelenggara module.
    case 'help.page.penyelenggara':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Penyelenggara kejuaraan') . '</p>';
      return $output;

    default:
  }
}
